### ISSUE TITLE
[libprotobuf WARNING ...] No syntax specified ...

### ISSUE THREAD

**Issue by glgrobe** [GobySoft/goby#42]
Warnings to become errors in future releases, using c++17.

[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: dccl/protobuf/option_extensions.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)

**Comment by tsaubergine** [comment]
This is a protoc warning, has nothing to do with the C++ compiler.

This has been worked-around in Goby3, I can backport if necessary. What version of Protobuf are you using where this has become an error?

**Comment by glgrobe** [comment]
Right, not sure why I posted the compiler. It just so happened that I noticed this after the compiler upgrade. I also recall doing minor Goby and DCCL upgrades. I'm using DCCL v3.0, and syntax="proto2". I can provide more versioned details on both of those on Monday, but this appears with protoc on the *.proto's. No backports necessary ATM, just wanted to report it. Sounds like you've got it handled.
